### ISSUE TITLE
Inconsistency in README

### ISSUE THREAD

**Issue by razius** [justwatchcom/elasticsearch_exporter#107]
In the README file you refer to tag version `1.0.1` but some of the configuration arguments like `es.indices` and `version` are not available for that version tag. 

First thing that you would do in this case is use the `latest` tag assuming there is a new release but that tag points to `1.0.1` instead of `1.0.2rc2` which would be latest.

It's a bit confusing.

```
flag provided but not defined: -es.indices
Usage of elasticsearch_exporter:
  -es.all
    	Export stats for all nodes in the cluster.
  -es.ca string
    	Path to PEM file that conains trusted CAs for the Elasticsearch connection.
  -es.client-cert string
    	Path to PEM file that conains the corresponding cert for the private key to connect to Elasticsearch.
  -es.client-private-key string
    	Path to PEM file that conains the private key for client auth when connecting to Elasticsearch.
  -es.timeout duration
    	Timeout for trying to get stats from Elasticsearch. (default 5s)
  -es.uri string
    	HTTP API address of an Elasticsearch node. (default "http://localhost:9200")
  -web.listen-address string
    	Address to listen on for web interface and telemetry. (default ":9108")
  -web.telemetry-path string
    	Path under which to expose metrics. (default "/metrics")
```

**Comment by zwopir** [comment]
Thanks for the heads up! The latest version is indeed 1.0.2rc.2. I will fix
the README as soon as possible

Am 18.11.2017 12:12 nachm. schrieb "Silviu Tantos" <notifications@github.com
>:

In the README file you refer to tag version 1.0.1 but some of the
configuration arguments like es.indices and version are not available for
that version tag.

First thing that you would do in this case is use the latest tag assuming
there is a new release but that tag points to 1.0.1 instead of 1.0.2rc2
which would be latest.

It's a bit confusing.

flag provided but not defined: -es.indices
Usage of elasticsearch_exporter:
  -es.all
    	Export stats for all nodes in the cluster.
  -es.ca string
    	Path to PEM file that conains trusted CAs for the Elasticsearch connection.
  -es.client-cert string
    	Path to PEM file that conains the corresponding cert for the
private key to connect to Elasticsearch.
  -es.client-private-key string
    	Path to PEM file that conains the private key for client auth
when connecting to Elasticsearch.
  -es.timeout duration
    	Timeout for trying to get stats from Elasticsearch. (default 5s)
  -es.uri string
    	HTTP API address of an Elasticsearch node. (default
"http://localhost:9200")
  -web.listen-address string
    	Address to listen on for web interface and telemetry. (default ":9108")
  -web.telemetry-path string
    	Path under which to expose metrics. (default "/metrics")

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/justwatchcom/elasticsearch_exporter/issues/107>, or mute
the thread
