### ISSUE TITLE
Allow Comma separated list of multiple ES servers

### ISSUE THREAD

**Issue by karthimohan** [justwatchcom/elasticsearch_exporter#117]
Hi there,

Thanks for this great exporter. I have been struggling to get the Prometheus exporter which supports older version i mean < 2.3.1. This works great. 

Currently functionality only allows single elastic server instance -es.uri=http:/serverA:9200.

It would be great if we can pass multiple server endpoints like 
-es.uri=http:/serverA:9200, serverB:9200,serverC:9200,

This way, even if Server A goes down, exporter still able to collect the data from the second server.

**Comment by dannyk81** [comment]
In general, your best approach should be to run an exporter on each Elasticsearch server and have prometheus scrape from all of them.

This is the best practice with regard to Prometheus exporters and solves your availability concerns.

**Comment by zwopir** [comment]
I totally agree with dannk81. To avoid duplicate time series you should then use `es.all=false` (which is the default - so you can simply don't specify the flag).

What are the problems you're struggling with on < 2.3.1?

**Comment by karthimohan** [comment]
@dannyk81 @zwopir Thanks for the response. Makes sense on what you suggested. I am going to try that. I might need to modify the docker image slightly to get the right remote ES.URL as i am running ElasticSearch cluster in a docker container on top of Marathon. 

What are the problems you're struggling with on < 2.3.1? --> I dont have any problems in get this exporter working. super simple. Thanks for that.

I was talking in general about other exporters which dont support the older version of ES. Not sure how i missed this one before :) May be not on top of the google search. Now it is though

**Comment by baoshengzhu** [comment]
Allow Comma separated list of multiple ES servers now?

**Comment by zwopir** [comment]
Hi @baoshengzhu,

no, the exporter doesn't support it. There are at least two things we have to think about if we want to support it:
- how the exporter selects the node to be queried from the provided list (the most used ES go client has a mechanism called node-sniffing). Also the retry logic (if any)
- consistency with the `-es.node/-es.all` flags. If the exporter queries different nodes on each scrape, you'll get garbage metrics unless you specify `es.all`  

After all it's "just" an exporter. If it can't query a node, the various `up` metrics will tell you so, which is part of the reason you are monitoring a cluster. I would clearly vote for code simplicity and consistent flag behavior instead of the requested feature.

**Comment by anjalin1001** [comment]
Hi @zwopir 

I am also in similar situation .
If we are using different exporters for each elasticsearch urls, please advise if we need different ports for each exporter? 
if 9108 is used for the ElasticExporter of ES1, which port can be given for the next ES ? 

PS: Elasticsearch is deployed in kubernetes in GCP .

Your  response is much appreciated.
Anjali N
