### ISSUE TITLE
What are the values for elasticsearch_cluster_health_status?

### ISSUE THREAD

**Issue by burton-scalefastr** [justwatchcom/elasticsearch_exporter#120]
I don't even see it defined the code...

**Comment by zwopir** [comment]
see https://github.com/justwatchcom/elasticsearch_exporter/blob/master/collector/cluster_health.go#L195 and
https://github.com/justwatchcom/elasticsearch_exporter/blob/master/collector/cluster_health.go#L275

So the values are 
```
elasticsearch_cluster_health_status{cluster="elasticsearch",color="green"} 1
elasticsearch_cluster_health_status{cluster="elasticsearch",color="red"} 0
elasticsearch_cluster_health_status{cluster="elasticsearch",color="yellow"} 0
```

**Comment by burton-scalefastr** [comment]
wait,, both read AND yellow are 0 ??

**Comment by dannyk81** [comment]
Indeed, because Green is 1

it means that cluster status is Green

**Comment by zwopir** [comment]
we chose this representation to avoid a made up mapping like
```
green = 1
yellow = 2
red = 3
```
(you can't have string values in prometheus - the json from ES contains a string in the cluster-health-status value)

**Comment by zsrinivas** [comment]
hey, any idea on how I can make a single stat panel in grafana with this kind of value format

**Comment by jpdstan** [comment]
@zsrinivas for a single stat panel in grafana you can do something like
```
max(elasticsearch_cluster_health_status{color="green",cluster=~"my_cluster"}) + ON(cluster) max(elasticsearch_cluster_health_status{color="yellow",cluster=~"my_cluster"})* 2 + ON(cluster) max(elasticsearch_cluster_health_status{color="red",cluster=~"my_cluster"}) * 3
```
and then create value mappings in the grafana dashboard to map the values 1, 2, 3 to green, yellow, and red respectively.

**Comment by QuanTran91** [comment]
Hi @jpdstan , I am just curios since I am a Promql newbie
What does the "ON(cluster) " mean here?
Thank a lot

**Comment by jpdstan** [comment]
@QuanTran91 you can think of them as SQL joins, i.e. "join results from left side with right side where `cluster` is the same". if you do not include the `ON(<labels>)`, then you will only "join" with a metric that has the EXACT same set of labels. `ON(<labels>)` lets you specify the label(s) to join on. it's not always necessary but it's recommended since labels are very dynamic and it is possible that the `green` metric may have labels that the `yellow` metric does not have, or vice versa.

read more here: https://prometheus.io/docs/prometheus/latest/querying/operators/#many-to-one-and-one-to-many-vector-matches
