### ISSUE TITLE
How to handle multiple exporters for elasticsearch

### ISSUE THREAD

**Issue by pvanderlinden** [justwatchcom/elasticsearch_exporter#126]
This is not really a bug, but I think this is more missing documentation.

Besides the cluster inside kubernetes we also have a cluster running on VM's, these are deployed with ansible, which means all of them will run exporter as well. This means the data is duplicated though, and I expected to fix this with setting `es.all` to `false`. Unfortunately this does not fix the duplication issue.

What is the correct way to handle this?

**Comment by zwopir** [comment]
Hi @pvanderlinden,

thanks for reporting this. The documentation might not be complete clear. Setting `es.all=false` changes the "deduplication" of the node-stats metrics only. 
For details see https://github.com/justwatchcom/elasticsearch_exporter/blob/master/collector/nodes.go#L1334

Unfortunately there is no way of further avoiding duplicate metrics (for example index level metrics) since  an exporter can't know what another exporter is exporting.

If the cluster is not to big, I'd suggest just activating one elasticsearch_exporter querying one of the cluster nodes. You then get all node stats from this exporter with `es.all=true`.

**Comment by pvanderlinden** [comment]
Thanks, the only problem I'm running into now is that I don't know how to restrict ansible to deploy the exporter on one node if that is even possible.

**Comment by zwopir** [comment]
couldn't you just specify a host variable in ansible and make the exporter-installing task conditional?
http://docs.ansible.com/ansible/latest/intro_inventory.html#host-variables
http://docs.ansible.com/ansible/latest/playbooks_conditionals.html

**Comment by pvanderlinden** [comment]
Thanks! Didn't expect you to actually solve this problem for me, but you got there first. The whole problem is solved now.

**Comment by zwopir** [comment]
you're welcome. I'm happy to help
