### ISSUE TITLE
first path segment in URL cannot contain colon

### ISSUE THREAD

**Issue by opsj** [justwatchcom/elasticsearch_exporter#148]
I am attempting to deploy the elasticsearch_exporter in openshift, requiring me to modify the ENTRYPOINT command in the Dockerfile as follows:
```
ENTRYPOINT /bin/elasticsearch_exporter -es.all -es.uri=https://host.name.com:9200 -es.ca=/path/to/ca/ca-file.pem -es.client-private-key=/path/to/key/es-key.pem -es.client-cert=/path/to/cert/es-cert.pem
```
Which results in the following error upon deployment:
```
level=error ts=2018-05-08T16:40:43.6397782Z caller=main.go:52 msg="failed to parse es.uri" err="parse -es.uri=https://host.name.com:9200:  first path segment in URL cannot contain colon"
```

I have tried the following variations of command line arguments:
1.
```
ENTRYPOINT /bin/elasticsearch_exporter "-es.all -es.uri=https://host.name.com:9200 -es.ca=/path/to/ca/ca-file.pem -es.client-private-key=/path/to/key/es-key.pem -es.client-cert=/path/to/cert/es-cert.pem"
```

2.
```
ENTRYPOINT /bin/elasticsearch_exporter -es.all -es.uri "https://host.name.com:9200" -es.ca=/path/to/ca/ca-file.pem -es.client-private-key=/path/to/key/es-key.pem -es.client-cert=/path/to/cert/es-cert.pem
```

3.
```
ENTRYPOINT /bin/elasticsearch_exporter "-es.all -es.uri="https://host.name.com:9200" -es.ca=/path/to/ca/ca-file.pem -es.client-private-key=/path/to/key/es-key.pem -es.client-cert=/path/to/cert/es-cert.pem"
```

Wondering if anyone has run into this issue, or if anyone has suggestions as a workaround

**Comment by opsj** [comment]
It was just a typo in this issue unfortunately. The error message still appears as follows:
```
level=error ts=2018-05-08T17:08:20.404326614Z caller=main.go:52 msg="failed to parse es.uri" err="parse -es.all -es.uri=https://host.name.com:9200  -es.ca=/path/to/ca/ca-file.pem -es.client-private-key=/path/to/key/es-monitoring-key.pem -es.client-cert=/path/to/cert/es-monitoring-cert.pem: first path segment in URL cannot contain colon"
```

**Comment by zwopir** [comment]
there must be an error in the dockerfile setup. The error messages states, that it can't parse
`-es.uri=https://host.name.com:9200` as URL (with -es.uri !!!). So there must be a duplicate -es.uri somewhere. You can reproduce net/url error message like so: https://play.golang.org/p/t3RCtIjbDmc

**Comment by zwopir** [comment]
I can reproduce the error with calling the exporter like this:
```
./elasticsearch_exporter -es.uri -es.uri=https://my.hostname.whatever:9200
```
I then get 
```
level=error ts=2018-05-09T08:50:03.517947833Z caller=main.go:50 msg="failed to parse es.uri" err="parse -es.uri=https://my.hostname.whatever:9200: first path segment in URL cannot contain colon"
```

**Comment by opsj** [comment]
I have verified that there are no duplicate `-es.uri` flags passed in. The setup I have works fine locally, but fails with that error when I deploy it to openshift.

**Comment by opsj** [comment]
I figured out what the issue was. I was passing in an environment variable in the openshift template as `ES_URI= -es.uri=https://some.hostname:9200` which is the same name as an environment variable used in the `main.go` file, causing the variable to be read in twice.

**Comment by artem-dronov** [comment]
The problem is not only in the docker on the host, when launched through the system unit, such an error:
`elasticsearch_exporter[16405]: level=error ts=2020-01-27T07:29:08.675384105Z caller=main.go:90 msg="failed to parse es.uri" err="parse \"10.32.20.39:9200\": first path segment in URL cannot contain colon"
`
Unit:

`[Unit]
Description=Prometheus Elastic Exporter
#Wants=network-online.target
After=network-online.target

[Service]
Type=simple
User=root
Group=root
#User=elasticsearch-exp
#Group=elasticsearch-exp
ExecReload=/bin/kill -HUP $MAINPID
ExecStart=/usr/local/bin/elasticsearch_exporter --web.listen-address="212.*.225.*:9114" --es.uri="10.*.20.*:9200"

SyslogIdentifier=elasticsearch_exporter
Restart=always
RestartSec=1

PrivateTmp=yes
ProtectHome=yes
NoNewPrivileges=yes

ProtectSystem=full


[Install]
WantedBy=multi-user.target
`
If you execute directly through the command line, then everything works:

`/usr/local/bin/elasticsearch_exporter --web.listen-address="212.*.225.*:9114" --es.uri="10.*.20.*:9200"`

`level=info ts=2020-01-27T07:33:57.410669859Z caller=clusterinfo.go:200 msg="triggering initial cluster info call"
level=info ts=2020-01-27T07:33:57.410799832Z caller=clusterinfo.go:169 msg="providing consumers with updated cluster info label"
level=info ts=2020-01-27T07:33:57.413413551Z caller=main.go:148 msg="started cluster info retriever" interval=5m0s
level=info ts=2020-01-27T07:33:57.413650816Z caller=main.go:188 msg="starting elasticsearch_exporter" addr=212.*.225.*:9114
`
System: Debain jessie

What could be the problem?
