### ISSUE TITLE
Read config from file

### ISSUE THREAD

**Issue by mrueg** [justwatchcom/elasticsearch_exporter#188]
Since `es.uri` can contain a password, it would be nice to read the config from a file. If it's in the command line it's likely to leak via top or other means.

**Comment by zwopir** [comment]
Hi Manuel,

you can specify the ES URI as environment variable `ES_URI`. So far only `ES_URI` is supported as "config-as-env", but the other commandline flags are available once https://github.com/justwatchcom/elasticsearch_exporter/issues/173 is implemented.

Config files are unlikely to be supported as running the exporter "plain" ( = non-docker or k8s) is probably best done via systemctl which supports specifying environment variables via file

**Comment by zwopir** [comment]
well, if you have the permission to read the `/proc/<pid>/environ` file, you can read the config file directly. So if I'm not terribly wrong, adding support for config files doesn't improve anything. Correct my, if I'm wrong, please.
viper is still worth evaluating for the project since it supports flag bindings which will make the transition from single-dash command line parameters to posix parameters a bit more smooth.
From a first impression, it's a tradeoff between clumsyness (sorry, spf13) and features...

**Comment by zwopir** [comment]
we decided to go with kingpin. So configuring via environment variables is supported, but not via config file
