### ISSUE TITLE
Readiness Probe and Liveness Probe Failing

### ISSUE THREAD

**Issue by amankedia** [justwatchcom/elasticsearch_exporter#261]
I have 2 elasticsearch clusters and 1 elasticsearch exporter pod/deployment which runs 2 containers, one for each of the clusters.

I have modified the ports for them to be 9210 and 9211 respectively.

The one on port 9210 is working fine and its ES cluster is also doing good.

The one on port 9211 is not working fine and its ES cluster has a lot of Unassigned shards.

I am not sure if there is any relation between the ES Cluster having Unassigned shards and the corresponding exporter failing.

Results from failing container

[root@elasticsearch-exporter-6cfcf67858-72xqf /]# curl -X GET elasticsearch-exporter-6cfcf67858-72xqf:9211/metrics curl: (7) Failed connect to elasticsearch-exporter-6cfcf67858-72xqf:9211; Connection refused [root@elasticsearch-exporter-6cfcf67858-72xqf /]# curl -X GET elasticsearch-exporter-6cfcf67858-72xqf:9211/ curl: (7) Failed connect to elasticsearch-exporter-6cfcf67858-72xqf:9211; Connection refused [root@elasticsearch-exporter-6cfcf67858-72xqf /]# curl -X GET elasticsearch-exporter-6cfcf67858-72xqf:9211 curl: (7) Failed connect to elasticsearch-exporter-6cfcf67858-72xqf:9211; Connection refused

Liveness and Readiness Probe Snippets (please ignore indentation issues, they are fine in the code base)
`readinessProbe:
 httpGet:
    port: 9211
    path: /metrics
    initialDelaySeconds: 15
	periodSeconds: 10
	timeoutSeconds: 2
livenessProbe:
  httpGet:
    port: 9211
    path: /metrics
    liveliness:
	initialDelaySeconds: 15
	periodSeconds: 10
	timeoutSeconds: 2
`

Describe pod shows the following:
`Warning  Unhealthy  8m (x153 over 3h)  kubelet, NODE_IP  Readiness probe failed: Get http://POD_IP:9211/metrics: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
  Warning  BackOff    3m (x748 over 3h)  kubelet, NODE_IP  Back-off restarting failed container
`

**Comment by zwopir** [comment]
the problem is probably the liveness/readiness probe *path* that you are using. Currently you are using `/metrics` which isn't a good idea, because a) it issues multiple ES HTTP API calls and b) doesn't respond in a timely manner suitable for health checking if the configured ES is unreachable/doesn't answer in time.

I would strongly recommend to use `/` or `/health` as health endpoint. `/health` is just a random name, in the code every path that is not `/metrics` falls back to the HTTP handler that handles `/`.
This way you can distinguish if it's a problem with the exporter/it's configuration or the ES it should monitor
