### ISSUE TITLE
Custom query result as metric

### ISSUE THREAD

**Issue by iyesin** [justwatchcom/elasticsearch_exporter#275]
Hello,
I'm searching for option to export result of custom elasticsearch query as a metric. Is there any way to do this with this exporter?

**Comment by zwopir** [comment]
Hello @iyesin,

this is not possible with this exporter. It's focus are operational metrics as opposite to custom queries on the index content.

**Comment by iyesin** [comment]
@zwopir thank you for quick reply.
I got it. My next question is: since operational metrics queried and received via same machinery as any other query, wouldn't it be wiser to widen set of the goals of this exporter and add custom queries support?

**Comment by zwopir** [comment]
except the machinery (querying a rest api) custom queries have not much in common with the API responses from the known operational endpoints.  Here the response format is well know. If you define custom queries, the result can be almost anything. Mapping custom responses to a numeric value ( = prometheus metric) with a type (gauges, counter, ...) and labels really gets complicated if you don't know the response format.

This is why I don't want to add custom metric support to this exporter. The costs of abstracting away the above complexity and having a exporter that can fail because of wrongly defined custom queries and mappings isn't worth the effort compared to writing a mini exporter that only exports a hand of custom metrics.

**Comment by iyesin** [comment]
Thank you for detailed reply, @zwopir!
I got your point.
