### ISSUE TITLE
elastic_exporter metric values are difference from kibana

### ISSUE THREAD

**Issue by alochym01** [justwatchcom/elasticsearch_exporter#323]
Hi

i use elasticsearch_exporter to monitor elasticsearch
Cluster topology
1. 01 master
2. 02 data nodes

from kibana values:
| Primary | Docs Count | Replicas |
|------------|-----------------|-------------|
| 2           |  9473429     |   1          |

from elasticsearch_exporter values
| Prometheus query | Values | 
|--------------------------|-----------------|
| elasticsearch_indices_docs_total{cluster="cluster",index="jaeger-span-2020-02-10",instance="192.168.56.10:9114",job="elasticsearch_exporter"}  | 18946858 |

elasticsearch_export's value is double docs count of kibana, is it right??

why is elasticsearch_exporter have 2 x kibana values

thank you

**Comment by mblaschke** [comment]
9473429 should be the count of `elasticsearch_indices_docs_primary` (only primary documents, without replicas)

`elasticsearch_indices_docs_total` all primary multiplied with number of replicas -> `9473429 * (1 + 1) = 18946858`

just guessing as this would make sense.

**Comment by alochym01** [comment]
thank you

**Comment by rikimaru0345** [comment]
Same issue here, is there a way we can get the number of replicats from the metrics? Or is there a way to filter a metric so it only contains the primary documents?

I'm using release version 1.1.0 and it doesn't report a metric named `elasticsearch_indices_docs_primary ` or `elasticsearch_indices_docs_total`.
Only: `elasticsearch_indices_docs`, and there is no label on it to differentiate primary/replica.

Is it because I'm using v1.1.0? Should I be using a newer version?
