### ISSUE TITLE
Trouble with starting elasticsearch exporter as binary

### ISSUE THREAD

**Issue by Tapa4ik** [justwatchcom/elasticsearch_exporter#332]
Hi! i run the following command 
in the docs i've read this

> The exporter fetches information from an ElasticSearch cluster on every scrape, therefore having a too short scrape interval can impose load on ES master nodes, particularly if you run with --es.all and --es.indices

and here;s my ExecStart from my SystemD unit file
`/opt/prometheus-exporters/elasticsearch-exporter/elasticsearch_exporter --es.uri http://192.168.1.12:9200  --es.timeout 5s  --web.listen-address :9108 --web.telemetry-path /metrics`

and this is okay? it will not impose load on my ES cluster? because i don't see any --es.all and --es.indices in my startup command?
thanks

**Comment by zwopir** [comment]
Hi @Tapa4ik,

I can't really say, because one important information is missing: The scrape interval you configured for the scrape job in you prometheus configuration (`prometheus.yml`).

But in the end you have to figure it out yourself. We're running the exporter with a 30s scrape interval with --es.all enabled on a  6 node cluster and are fine. Going higher in the scraper frequency doesn't lead to more insights anyways ...

**Comment by Tapa4ik** [comment]
@zwopir sorry my scrape interval is default to 30s but i want to remove --es.all 
and how to remove this one? using flag?

**Comment by zwopir** [comment]
I don't quite understand. if you don't specify `--es.all` at the exporter will only expose the metrics from the node that is configured via `--es.uri`. So the flag defaults to `false`

**Comment by Tapa4ik** [comment]
@zwopir sorry for my english, thanks a lot!
